#  Build & Run FHIR Publisher, and push output to gh-pages

langauge: java

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

script: ./build.sh
sudo: required
notifications:
  email: []
  webhooks:
    - https://chat.fhir.org/api/v1/external/travis?stream=committers&topic=ci-notifications&api_key=IelOy1KhccEy3QpRIeOrtQUTqw98Kvr8

before_install:
  - openssl aes-256-cbc -K $encrypted_7d142fa10e4e_key -iv $encrypted_7d142fa10e4e_iv -in deploy.build.fhir.org.enc -out ~/deploy.build.fhir.org -d
  - chmod 600 ~/deploy.build.fhir.org

after_success:
  - cd publish
  - echo -e "Host build.fhir.org\n  Compression yes\n  StrictHostKeyChecking no\n  User fhir_upload\n  IdentityFile ~/deploy.build.fhir.org" > ~/.ssh/config
  - tar czf - * | ssh build.fhir.org "mkdir -p /var/www/uploading/$TRAVIS_BUILD_ID && cd /var/www/uploading/$TRAVIS_BUILD_ID && ((while true; do sleep 10; du -hs .; done) & tar xzf - && date --iso-8601 > /var/www/uploading/$TRAVIS_BUILD_ID/done.txt && kill %1)"
  - ssh build.fhir.org "test -e /var/www/uploading/$TRAVIS_BUILD_ID/done.txt && mv /var/www/build.fhir.org /var/www/replaced_by_$TRAVIS_BUILD_ID && mv /var/www/uploading/$TRAVIS_BUILD_ID /var/www/build.fhir.org && rm -rf /var/www/replaced_by_$TRAVIS_BUILD_ID"
  - echo -e "Host 35.185.32.255\n  Compression yes\n  StrictHostKeyChecking no\n  User fhir_upload\n  IdentityFile ~/deploy.build.fhir.org" > ~/.ssh/config
  - ssh 35.185.32.255 ./publish
