swagger: 2.0

info:  title: SDC Form Designer
  description: This profile defines the expected capabilities of the ''SDC Form Designer'' role when conforming to the S&I Framework's [[index|Structured Data Capture FHIR implementation guide]].  This role is responsible for defining forms ([[Questionnaire]] resource instances) that include references to [[DataElement]] resouces which define the meaning of particular questions and can be used to aid in pre-populating and auto-populating forms.
  version: 2.0
  # contact:
    # end user to fill out
  license:
    name: null

# host: [user to provide]
# basePath: [user to provide]
schemes:
  - https
  # - http this would not normally be allowed (see doco)
consumes:
produces:
