swagger: 2.0

info:  title: SDC Form Filler
  description: This profile defines the expected capabilities of the ''SDC Form Filler'' role when conforming to the S&I Framework's [[index|Structured Data Capture FHIR implementation guide]].  This role is responsible for retrieving pre-defined forms, requesting pre-population of forms and/or auto-populating forms, guiding the user through verifying populated data and submitting completed or partially-completed forms.<br/>Note that Form Fillers may also take on the role of [[sdc-form-archiver|Form Archiver]] if they have a requirement to retain the completed version of a form (and potentially the source data that was used to complete it).
  version: 2.0
  # contact:
    # end user to fill out
  license:
    name: null

# host: [user to provide]
# basePath: [user to provide]
schemes:
  - https
  # - http this would not normally be allowed (see doco)
consumes:
produces:
